"use client";
import Link from 'next/link';
import { useState } from 'react';
import AdminShell from '../../../../components/admin/AdminShell';

const fields = [['name', 'Name'], ['company', 'Company'], ['email', 'Email'], ['phone', 'Phone'], ['loginUsername', 'Login username'], ['password', 'Temporary password']];

export default function NewClientPage() {
  const [form, setForm] = useState({ name: '', company: '', email: '', phone: '', loginUsername: '', password: '' });
  const [result, setResult] = useState(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  async function submit(event) { event.preventDefault(); setSaving(true); setError(''); setResult(null); try { const response = await fetch('/api/admin/clients', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to create client'); setResult({ ...data, password: form.password }); setForm({ name: '', company: '', email: '', phone: '', loginUsername: '', password: '' }); } catch (reason) { setError(reason.message); } finally { setSaving(false); } }
  return <AdminShell breadcrumb="Clients / New"><main className="max-w-3xl mx-auto px-8 py-10"><Link href="/admin/clients" className="text-sm text-[var(--admin-teal)]">← Back to clients</Link><h1 className="text-3xl font-semibold mt-5">Create client</h1><p className="text-[var(--admin-muted)] mt-2 mb-7">Create the account and share its credentials securely.</p>{error && <p className="mb-5 text-red-700 bg-red-50 p-4 rounded-lg text-sm">{error}</p>}{result && <div className="admin-card mb-6 border-emerald-200 bg-emerald-50 p-5"><h2 className="font-bold text-emerald-800">Client created</h2><p className="text-sm text-emerald-900/70 mt-2">Save or share these credentials securely. The password will not be shown again.</p><dl className="mt-4 grid sm:grid-cols-2 gap-3"><div><dt className="admin-label">Username</dt><dd>{result.loginUsername}</dd></div><div><dt className="admin-label">Password</dt><dd>{result.password}</dd></div></dl><Link href={`/admin/clients/${result.id}`} className="inline-block mt-5 text-emerald-700 underline text-sm">Open client profile</Link></div>}<form onSubmit={submit} className="admin-card grid sm:grid-cols-2 gap-4 p-6">{fields.map(([name, label]) => <label key={name} className="text-xs font-medium text-[var(--admin-ink)]">{label}<input required={['name', 'email', 'loginUsername', 'password'].includes(name)} type={name === 'password' ? 'password' : name === 'email' ? 'email' : 'text'} name={name} value={form[name]} onChange={update} className="mt-2 w-full p-3 rounded-lg border border-[#d6e2df] outline-none focus:border-[var(--admin-teal)]" /></label>)}<button disabled={saving} className="sm:col-span-2 bg-[var(--admin-teal)] text-white disabled:opacity-50 px-5 py-3 rounded-lg font-semibold">{saving ? 'Creating...' : 'Create client'}</button></form></main></AdminShell>;
}